### ISSUE TITLE
Why do you create flatten vector of logspec?

### ISSUE THREAD

**Issue by MasazI** [aqibsaeed/Urban-Sound-Classification#1]
Why do you do following a processing?
 logspec = logspec.T.flatten()[:, np.newaxis].T
I think this processing might break logspec feature.

**Comment by aqibsaeed** [comment]
Short answer, for easy appending of logspec and afterwards calculation of deltas. You can reshape/use different shape and use np.vstack, but this is one easy way I found at that time. I haven't faced any issue while using this, please give it a try if you find any issues, submit a pull request.
