### ISSUE TITLE
Error Running the Notebook

### ISSUE THREAD

**Issue by yujulucy** [aqibsaeed/Urban-Sound-Classification#10]
![screenshot from 2017-09-06 21-20-53](https://user-images.githubusercontent.com/12662268/30114115-ad992dbc-92cb-11e7-84f1-8bcc27ee9dff.png)

Hi, when I tried running the notebook "Urban Sound Classification using CNN.ipynb", I came across this error on Jupyter Notebook. May I know what is wrong?

**Comment by aqibsaeed** [comment]
Sorry this error is not clear to me. May be I can be of some help, if you share full error message.

**Comment by yujulucy** [comment]
The full error message is as follow:

WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/python/util/tf_should_use.py:175: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-9cbbefed3b68> in <module>()
      8         batch_y = train_y[offset:(offset + batch_size), :]
      9 
---> 10         _, c = session.run([optimizer, cross_entropy],feed_dict={X: batch_x, Y : batch_y})
     11         cost_history = np.append(cost_history,c)
     12 

/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.pyc in run(self, fetches, feed_dict, options, run_metadata)
    893     try:
    894       result = self._run(None, fetches, feed_dict, options_ptr,
--> 895                          run_metadata_ptr)
    896       if run_metadata:
    897         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.pyc in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1098                 'Cannot feed value of shape %r for Tensor %r, '
   1099                 'which has shape %r'
-> 1100                 % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
   1101           if not self.graph.is_feedable(subfeed_t):
   1102             raise ValueError('Tensor %s may not be fed.' % subfeed_t)

ValueError: Cannot feed value of shape (0, 0) for Tensor u'Placeholder_1:0', which has shape '(?, 10)'

**Comment by aqibsaeed** [comment]
The error message suggest the label place holder's shape and the data that fed have different shapes. I would recommend you to print train_y to make sure it has correct shape and data.
