### ISSUE TITLE
RNN code doesn't run

### ISSUE THREAD

**Issue by alimirsharji** [aqibsaeed/Urban-Sound-Classification#13]
Hi
I tried to run your RNN code but I got this error:
Traceback (most recent call last):
  File "/home/sam95/PycharmProjects/SED_using_CNN/RNN_SED.py", line 43, in <module>
    tr_features,tr_labels = extract_features(parent_dir,tr_sub_dirs)
  File "/home/sam95/PycharmProjects/SED_using_CNN/RNN_SED.py", line 25, in extract_features
    if(len(sound_clip[start:end]) == window_size):
TypeError: slice indices must be integers or None or have an __index__ method

can you help me solving this problem?

**Comment by aqibsaeed** [comment]
Can you verify if sound_clip is not empty! I would suggest to add a if check before if(len(sound_clip[start:end]) == window_size). Let me know if this helps!

**Comment by alimirsharji** [comment]
i'm beginner in python and deep learning :))
can you clear me to add what?
and another q is how to use datasets? i mean i created a folder in my project folder in pycharm and named it Sound-Data and copy two of folders in dataset in there, is it ok?

**Comment by aqibsaeed** [comment]
Something like that:
```
if(len(sound_clip) > 0):
     for (start,end) in windows(sound_clip,window_size):
```
About dataset: the code expect Sound-Data parent directory (with all the folds) within the same folder as of your notebook.

**Comment by alimirsharji** [comment]
Tnx
I'm running your NN code now and waiting for its respond
How much was your accuracy in CNN? For me it was near 20%
Problem is about code or something else?

**Comment by aqibsaeed** [comment]
This problem is not easy to solve! Keep trying different configuration and architectures :) Happy coding!

**Comment by sammir95** [comment]
:))
What do you think about it? is it about size of dataset? I want to use this tricks:
1)Enlarge dataset
2)Using drop out
3)Make layers more deep
4)Using some picture classification architecture like as AlexNet or Resnet and...
did you try this?
