### ISSUE TITLE
Dimensionality mismatch in RNN code

### ISSUE THREAD

**Issue by manojpamk** [aqibsaeed/Urban-Sound-Classification#14]
Hello,

The dimensions of the extracted features are supposed to be `[None,bands,frames]`, i.e `[None, 20, 41]`.
However, the placeholder for x expects dimensions `[None,n_steps,n_input]` which turns out to be `[None,41,20]`. 
I encountered this error while trying to train the RNN for another dataset. Am I missing something?

**Comment by aqibsaeed** [comment]
This might be correct! and maybe I confused between the two. It's been a while since I looked into this code. Aren't we going to handle bands as features (n_input) and frames as time steps (n_steps)?

**Comment by manojpamk** [comment]
Yes, that is right. So, the corresponding line inside `extract_features` would be
`features = np.asarray(mfccs).reshape(len(mfccs),frames,bands)`

**Comment by aqibsaeed** [comment]
Sounds right to me! Updated. Thanks!
