### ISSUE TITLE
Run your code

### ISSUE THREAD

**Issue by dheerajiiitv** [aqibsaeed/Urban-Sound-Classification#15]
Please tell me how to run your code

**Comment by aqibsaeed** [comment]
Install [anaconda python distribution ](https://www.anaconda.com/download/).
Install [Tensorflow](https://www.tensorflow.org/install/)
Download/Clone the repository to desktop
Open terminal type: jupyter notebook
Open the desired notebook that you want to run
Make sure data/file paths are properly set
