### ISSUE TITLE
Why you didn't use apply_max_pool() function?

### ISSUE THREAD

**Issue by Joanna1212** [aqibsaeed/Urban-Sound-Classification#17]
You defined it in your CNN code, but you didn't use this function.
I want to know if there is no need to use it or you forget it?
According to the paper you referenced in your blog, there should be max_pool operation.

And i run your code on UrbanSound8K data set, the loss didn't convergence.
Do you have a good result?

**Comment by aqibsaeed** [comment]
Thank you for your interest. Please look into the paper mentioned in the blog post. The purpose of this code is to give an idea how to apply deep learning on sound dataset so that others can optimize the architecture for best performance.
