### ISSUE TITLE
Getting the kernel restartig error too frequently

### ISSUE THREAD

**Issue by Anirudh257** [aqibsaeed/Urban-Sound-Classification#20]
I am trying to extract features using the tutorial: http://aqibsaeed.github.io/2016-09-03-urban-sound-classification-part-1/.  I have downloaded the required dataset but whenever I am running the code, I am getting this error.

![screenshot from 2018-01-22 20-04-26](https://user-images.githubusercontent.com/16001446/35225878-7bda5494-ffaf-11e7-97ac-9b9814aa4cab.png)

What can be the reasons for this?

**Comment by bazilione** [comment]
Have the same issue.

**Comment by gbernal** [comment]
I'm getting the same error, can someone please suggest a fix. Thank you

**Comment by Anirudh257** [comment]
It was a memory issue. I was able to run the code properly on Google Colab.
