### ISSUE TITLE
Notebook

### ISSUE THREAD

**Issue by annisaabuhamid** [aqibsaeed/Urban-Sound-Classification#21]
@aqibsaeed, does this model able to run in python without using notebook?
Thank you

**Comment by aqibsaeed** [comment]
Yes. Why not :)

**Comment by annisaabuhamid** [comment]
means i have to change from ipython to python?
![screenshot 3](https://user-images.githubusercontent.com/32840015/36963335-bc2108fa-208d-11e8-8ca5-0fcc6127a384.png)
is it related?

**Comment by aqibsaeed** [comment]
Just copy the code in a file and save as python file (with .py extension)  
and execute it via command line as: python <file_name>.py
