### ISSUE TITLE
Problem about the window sizes on different dataset

### ISSUE THREAD

**Issue by dertuncay** [aqibsaeed/Urban-Sound-Classification#25]
I'm using different dataset (number of data: 538) with the CNN code. Length of each data differs from each other. I realize that some of the data is not even analyzed since it didn't satisfy the if(len(eq_data[start:end]) == window_size)

I tried the change the window_size argument but then I got errors such as (window_size = 256)

> Traceback (most recent call last):
  File "mac_learn_spec_cnn.py", line 112, in <module>
    features,labels = extract_features(parent_dir)
  File "mac_learn_spec_cnn.py", line 97, in extract_features
    log_specgrams = np.asarray(log_specgrams).reshape(len(log_specgrams),bands,frames,1)
ValueError: cannot reshape array of size 1509480 into shape (1198,60,41,1)

What would you recommend me to overcome this problem?

**Comment by aqibsaeed** [comment]
I would suggest padding them with zeros at the end to make them of equal length. 
See this: https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/sequence/pad_sequences
