### ISSUE TITLE
How to organize the datasets?

### ISSUE THREAD

**Issue by jenweilee** [aqibsaeed/Urban-Sound-Classification#26]
The datasets of UrbanSound8K is organized as follows:
UrbanSound8K
---audio
------fold1
------fold2
------fold3
------fold4
------fold5
------fold6
------fold7
------fold8
------fold9
------fold10
---metadata

So, should I first create a directory named Sound-Data,
then copy the fold1 and fold2 to be the sub-directory of directory Sound-Data?
Is there something wrong?

Thank you.

**Comment by aqibsaeed** [comment]
Yes, seems ok to me. Sound-Data directly contains fold1,...fold10
