### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by caglarerennn** [aqibsaeed/Urban-Sound-Classification#36]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-8-43aa44921d37> in <module>
      5                   'fold9','fold10'])
      6 for sub_dir in sub_dirs:
----> 7     features, labels = extract_features(parent_dir,sub_dir)
      8     np.savez("{0}{1}".format(save_dir, sub_dir), 
      9              features=features,

<ipython-input-2-2f2892140ebd> in extract_features(parent_dir, sub_dirs, file_ext, bands, frames)
     12         segment_log_specgrams, segment_labels = [], []
     13         sound_clip,sr = librosa.load(fn)
---> 14         label = int(fn.split('/')[2].split('-')[1])
     15         for (start,end) in _windows(sound_clip,window_size):
     16             if(len(sound_clip[start:end]) == window_size):

IndexError: list index out of range

**Comment by aqibsaeed** [comment]
Please make sure the directory structure is same.

**Comment by synaption** [comment]
What should the directory structure be?  I am having the same error.

**Comment by aqibsaeed** [comment]
I kept the original directory structure. Please try to debug by printing sub_dirs to make sure that files/directories are read correctly.

**Comment by Machoney** [comment]
How about `fn.split('/')[-1]` instead of `fn.split('/')[2]`?
Then you can use your own path.
