### ISSUE TITLE
ValueError: all the input array dimensions except for the concatenation axis must match exactly

### ISSUE THREAD

**Issue by GiuseppePegasus** [aqibsaeed/Urban-Sound-Classification#37]
Error at the row:

tr_features, tr_labels = parse_audio_files(parent_dir, tr_sub_dirs)

  File "/Users/giuseppe/anaconda3/lib/python3.7/site-packages/numpy/core/shape_base.py", line 283, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)

ValueError: all the input array dimensions except for the concatenation axis must match exactly

**Comment by aqibsaeed** [comment]
It is due to having varying dimension of arrays that you are trying to stack. Please make sure the each array has dimension (or number of features).
