### ISSUE TITLE
Urban Sound Classification using CNN.ipynb test accuracy 0.149?

### ISSUE THREAD

**Issue by yucc2018** [aqibsaeed/Urban-Sound-Classification#4]
I run the Urban Sound Classification using CNN.ipynb and got a test accuracy of 0.149.  and the accuracy in paper  Environmental sound classification with convolutional neural networks by Karol J. Piczak. is more than 0.5. I wonder whether any code goes wrong? thanks

**Comment by aqibsaeed** [comment]
The model discussed in blogpost is not proposed by Karol J. Piczak. I mentioned clearly Karol model/idea was used as inspiration. Also, I would like to mention this is not simple problem to solve. That's why try training deep models and experiment with many different ideas.
