### ISSUE TITLE
Hardcoded path to sound files in `Urban Sound Classification using NN`

### ISSUE THREAD

**Issue by kubark42** [aqibsaeed/Urban-Sound-Classification#6]
https://github.com/aqibsaeed/Urban-Sound-Classification/blob/3f41ec2094f12107f9d336a12cb853b76f79e264/Urban%20Sound%20Classification%20using%20NN.ipynb does not run correctly. Specifically, the block

```
cost_history = np.empty(shape=[1],dtype=float)
y_true, y_pred = None, None
with tf.Session() as sess:
    sess.run(init)
    for epoch in range(training_epochs):            
        _,cost = sess.run([optimizer,cost_function],feed_dict={X:train_x,Y:train_y})
        cost_history = np.append(cost_history,cost)
    
    y_pred = sess.run(tf.argmax(y_,1),feed_dict={X: test_x})
    y_true = sess.run(tf.argmax(test_y,1))
```
yields the following error:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-12-62c28f30e413> in <module>()
      4     sess.run(init)
      5     for epoch in range(training_epochs):
----> 6         _,cost = sess.run([optimizer,cost_function],feed_dict={X:train_x,Y:train_y})
      7         cost_history = np.append(cost_history,cost)
      8 

/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in run(self, fetches, feed_dict, options, run_metadata)
    787     try:
    788       result = self._run(None, fetches, feed_dict, options_ptr,
--> 789                          run_metadata_ptr)
    790       if run_metadata:
    791         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _run(self, handle, fetches, feed_dict, options, run_metadata)
    973                 'Cannot feed value of shape %r for Tensor %r, '
    974                 'which has shape %r'
--> 975                 % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
    976           if not self.graph.is_feedable(subfeed_t):
    977             raise ValueError('Tensor %s may not be fed.' % subfeed_t)

ValueError: Cannot feed value of shape (0, 0) for Tensor u'Placeholder_1:0', which has shape '(?, 10)'
```

**Comment by aqibsaeed** [comment]
Please make sure that `train_y` have the correct shape and required data by printing it.

**Comment by kubark42** [comment]
Thanks, I see the problem now. There are certain places where paths are hardcoded, and one of them is `parent_dir = 'Sound-Data'`. If this is set to an absolute path, e.g. where I have located the downloaded sound files, then the line `labels = np.append(labels, fn.split('/')[2].split('-')[1])` fails. This can be changed to 

`labels = np.append(labels, fn.split('/')[-1].split('-')[1])`

and it seems to work as expected.

I really appreciate the rapid response!

P.S. Although now I receive the following warning when running `features, labels = parse_audio_files(parent_dir,sub_dirs)`:

```
/usr/local/lib/python2.7/site-packages/librosa/core/pitch.py:145: UserWarning: Trying to estimate tuning from empty frequency set.
  warnings.warn('Trying to estimate tuning from empty frequency set.')
```

**Comment by kubark42** [comment]
P.S. Although now I have the following warning when running `features, labels = parse_audio_files(parent_dir,sub_dirs)`:

```
/usr/local/lib/python2.7/site-packages/librosa/core/pitch.py:145: UserWarning: Trying to estimate tuning from empty frequency set.
  warnings.warn('Trying to estimate tuning from empty frequency set.')
```

**Comment by aqibsaeed** [comment]
Not sure about the warning. Please look into the documentation of Librosa for that. Make sure the audio file read is not empty before you extract features from it!

**Comment by kubark42** [comment]
> Make sure the audio file read is not empty before you extract features from it!

Good idea.  I'm using the UrbanSound8K dataset, I threw in a line to print out which file it is being parsed from the set. I should be able to report back if when/if it throws that warning a second time.

**Comment by jaminearly96** [comment]
Hi there, can @aqibsaeed please clarify the method of defining the file paths and what changes need to be made in the code. Should I be running the python code in a directory called Sound-Data (with all the fold folders)
