### ISSUE TITLE
`training_epochs` not defined in `Urban Sound Classification using CNN.ipynb`

### ISSUE THREAD

**Issue by kubark42** [aqibsaeed/Urban-Sound-Classification#7]
https://github.com/aqibsaeed/Urban-Sound-Classification/blob/5d913af248552e6cb3f635306f64faccd3d247af/Urban%20Sound%20Classification%20using%20CNN.ipynb uses `training_epochs`, but this is not defined. Perhaps this was intended to be `training_iterations` instead?

**Comment by aqibsaeed** [comment]
Fixed.
